# Generated by Django 5.1.4 on 2025-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='TEMP_CODE', max_length=10, unique=True, verbose_name='Course code'),
        ),
    ]
